version: '3.1'

services:
  covid0-bot:
    image: covidzero/slackbot:latest
    build: .
    environment:
      SLACK_TOKEN:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_S3_REGION:
      AWS_S3_BUCKET:
    volumes:
      - ./output:/tmp/covid0-slackbot/output/